GET http://localhost:3005/

###
POST http://localhost:3005/users/signup
Content-Type: application/json

{   
    "email": "ramakrishna.oguri@gmail.com",
    "fullName" : "Rama Krishna",
    "username" : "rami123",
    "password" : "qwerty"
}

###

POST http://localhost:3005/login
Content-Type: application/json

{
    "username" : "madhu123",
    "password" : "madhu123"
}

###
GET http://localhost:3005/home/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1MTIzIiwiaWF0IjoxNjIyODk1OTM4fQ.CD4B4azw5SV5-wX3P36zn4BGwUH7tgpSIkhps5yC1hU

###
GET http://localhost:3005/home/posts/4/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1MTIzIiwiaWF0IjoxNjIyODk1OTM4fQ.CD4B4azw5SV5-wX3P36zn4BGwUH7tgpSIkhps5yC1hU

###
GET http://localhost:3005/home/friendsuggestions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdnlhMTIzIiwiaWF0IjoxNjIzMzI0OTk2fQ.iTsncLgjtMMfKxqfiola7FgIc32jjUuWG8CeQ0wpM0k

### 
POST http://localhost:3005/home/posts/8/likes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1MTIzIiwiaWF0IjoxNjIzNTc5MTg4fQ.-zPjzoWnhOlly43mXNMKYX79Nfyl7lS-foCTmEwLTnY

{
    "likedTime": "2021-06-13 16:17:10",
    "liked": false
}

###
GET http://localhost:3005/home/post/11/liked
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1MTIzIiwiaWF0IjoxNjIzNTc5MTg4fQ.-zPjzoWnhOlly43mXNMKYX79Nfyl7lS-foCTmEwLTnY

###
POST http://localhost:3005/home/posts/0/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hZGh1MTIzIiwiaWF0IjoxNjIzNTc5MTg4fQ.-zPjzoWnhOlly43mXNMKYX79Nfyl7lS-foCTmEwLTnY

{
    "comment":"Hello, It is beautiful!",
    "commentedTime":"2021-06-13 16:17:10"
}