GET http://localhost:3005/

###
POST http://localhost:3005/users/signup
Content-Type: application/json

{   
    "email": "ramakrishna.oguri@gmail.com",
    "full_name" : "Rama Krishna",
    "username" : "rami123",
    "password" : "qwerty"
}

###

POST http://localhost:3005/login
Content-Type: application/json

{
    "username" : "rami123",
    "password" : "qwerty"
}